pipeline {
    agent any

    environment {
        IMAGE_NAME = "jobnudge-backend"
        CONTAINER_NAME = "jobnudge-backend-container"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'dev01', url: 'https://github.com/kaustubh8shelar/JobPortal.git'
            }
        }

        stage('Build App') {
            steps {
                dir('job-portal-server') {
                    bat '''
                        mvnw.cmd clean package -DskipTests
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('job-portal-server') {
                    script {
                        dockerImage = docker.build("${IMAGE_NAME}")
                    }
                }
            }
        }

         stage('Run Backend Container') {
                    environment {
                        MONGO_DATABASE = "job-portal-db"
                        MONGO_USER = "kaustubh8shelar"
                        MONGO_PASS = "07XhFUfyqSIh23xV"
                        MONGO_CLUSTER = "cluster0.zgk3h.mongodb.net"
                    }
                    steps {
                        bat """
                        docker rm -f ${CONTAINER_NAME} || exit 0
                        docker run -d --name ${CONTAINER_NAME} ^
                            -e MONGO_DATABASE=${MONGO_DATABASE} ^
                            -e MONGO_USER=${MONGO_USER} ^
                            -e MONGO_PASS=${MONGO_PASS} ^
                            -e MONGO_CLUSTER=${MONGO_CLUSTER} ^
                            -p 8080:8080 ${IMAGE_NAME}
                        """
                    }
                }
    }

    post {
        success {
            echo "Application deployed successfully!"
        }
        failure {
            echo "Build or deployment failed!"
        }
    }
}