pipeline {
    agent any

    environment {
        IMAGE_NAME = "jobnudge"
        CONTAINER_NAME = "jobnudge-container"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'dev01', url: 'https://github.com/kaustubh8shelar/JobPortal.git'
            }
        }

        stage('Build App') {
            steps {
                dir('job-portal-server') {
                    bat '''
                        mvnw.cmd clean package -DskipTests
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('job-portal-server') {
                    script {
                        dockerImage = docker.build("${IMAGE_NAME}")
                    }
                }
            }
        }

         stage('Run Container') {
                    environment {
                        MONGO_DATABASE = credentials('MONGO_DATABASE')
                        MONGO_USER = credentials('MONGO_USER')
                        MONGO_PASS = credentials('MONGO_PASS')
                        MONGO_CLUSTER = credentials('MONGO_CLUSTER')
                    }
                    steps {
                        bat """
                        docker rm -f ${CONTAINER_NAME} || exit 0
                        docker run -d --name ${CONTAINER_NAME} ^
                            -e MONGO_DATABASE=${MONGO_DATABASE} ^
                            -e MONGO_USER=${MONGO_USER} ^
                            -e MONGO_PASS=${MONGO_PASS} ^
                            -e MONGO_CLUSTER=${MONGO_CLUSTER} ^
                            -p 8080:8080 ${IMAGE_NAME}
                        """
                    }
                }
    }

    post {
        success {
            echo "Application deployed successfully!"
        }
        failure {
            echo "Build or deployment failed!"
        }
    }
}