pipeline {
    agent any

    environment {
        IMAGE_NAME = "jobnudge"
        CONTAINER_NAME = "jobnudge-container"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'dev01', url: 'https://github.com/kaustubh8shelar/JobPortal.git'
            }
        }

        stage('Build App') {
			steps {
				dir('job-portal-server') {
					sh '''
						chmod +x mvnw
						./mvnw clean package -DskipTests
					'''
				}
			}
		}


        stage('Build Docker Image') {
            steps {
                dir('job-portal-server') {
                    script {
                        dockerImage = docker.build("${IMAGE_NAME}")
                    }
                }
            }
        }

        stage('Run Container') {
            steps {
                sh """
                docker rm -f ${CONTAINER_NAME} || true
                docker run -d --name ${CONTAINER_NAME} -p 8080:8080 ${IMAGE_NAME}
                """
            }
        }
    }

    post {
        success {
            echo "Application deployed successfully!"
        }
        failure {
            echo "Build or deployment failed!"
        }
    }
}